import UserModel from 'models/UserModel';
import { MessageModel } from '../models/MessageModel';

export const users: Array<UserModel> = [
    {
        id: 1,
        first_name: 'Brett',
        last_name: 'Lloyd-Williams',
        phone_no: '9603133120',
        gender: 'Female',
        image_url: 'https://robohash.org/quissitlaudantium.jpg?size=50x50&set=set1',
    },
    {
        id: 2,
        first_name: 'Waldo',
        last_name: 'Housby',
        phone_no: '7228654799',
        gender: 'Male',
        image_url: 'https://robohash.org/voluptatemsimiliquedignissimos.jpg?size=50x50&set=set1',
    },
    {
        id: 3,
        first_name: 'Brad',
        last_name: 'Grayshan',
        phone_no: '9142359368',
        gender: 'Male',
        image_url: 'https://robohash.org/solutasednumquam.bmp?size=50x50&set=set1',
    },
    {
        id: 4,
        first_name: 'Selia',
        last_name: 'Bruhnsen',
        phone_no: '9306864668',
        gender: 'Female',
        image_url: 'https://robohash.org/omnisvoluptasut.bmp?size=50x50&set=set1',
    },
    {
        id: 5,
        first_name: 'Lionello',
        last_name: 'Durdy',
        phone_no: '4893074071',
        gender: 'Male',
        image_url: 'https://robohash.org/nonrepudiandaevoluptate.png?size=50x50&set=set1',
    },
    {
        id: 6,
        first_name: 'Neils',
        last_name: 'Castangia',
        phone_no: '2255007588',
        gender: 'Male',
        image_url: 'https://robohash.org/iustoenimlabore.bmp?size=50x50&set=set1',
    },
    {
        id: 7,
        first_name: 'Pepi',
        last_name: 'Saggs',
        phone_no: '4484648930',
        gender: 'Female',
        image_url: 'https://robohash.org/quosintest.bmp?size=50x50&set=set1',
    },
    {
        id: 8,
        first_name: 'Aldwin',
        last_name: 'Bulbrook',
        phone_no: '8642014282',
        gender: 'Male',
        image_url: 'https://robohash.org/saepevoluptasest.bmp?size=50x50&set=set1',
    },
    {
        id: 9,
        first_name: 'Hamid',
        last_name: 'Towl',
        phone_no: '5065906215',
        gender: 'Male',
        image_url: 'https://robohash.org/suntetcumque.jpg?size=50x50&set=set1',
    },
    {
        id: 10,
        first_name: 'Wendall',
        last_name: 'Stokes',
        phone_no: '7927599783',
        gender: 'Male',
        image_url: 'https://robohash.org/facilisomnisaut.png?size=50x50&set=set1',
    },
];

export const dummyMessage: Array<MessageModel> = [
    {
        id: 1,
        message: 'Diverse bi-directional data-warehouse',
        created_at: 1,
        sender_id: 1,
    },
    {
        id: 2,
        message: 'Assimilated uniform paradigm',
        created_at: 2,
        sender_id: 2,
    },
    {
        id: 3,
        message: 'Total optimal hierarchy',
        created_at: 3,
        sender_id: 1,
    },
    {
        id: 4,
        message: 'Configurable foreground help-desk',
        created_at: 4,
        sender_id: 1,
    },
    {
        id: 5,
        message: 'Reverse-engineered optimal workforce',
        created_at: 5,
        sender_id: 2,
    },
    {
        id: 6,
        message: 'Polarised cohesive conglomeration',
        created_at: 6,
        sender_id: 2,
    },
    {
        id: 7,
        message: 'Advanced well-modulated firmware',
        created_at: 7,
        sender_id: 2,
    },
    {
        id: 8,
        message: 'Universal scalable challenge',
        created_at: 8,
        sender_id: 2,
    },
    {
        id: 9,
        message: 'Front-line dedicated open architecture',
        created_at: 9,
        sender_id: 1,
    },
    {
        id: 10,
        message: 'Ergonomic 4th generation process improvement',
        created_at: 10,
        sender_id: 2,
    },
    {
        id: 11,
        message: 'De-engineered impactful support',
        created_at: 11,
        sender_id: 2,
    },
    {
        id: 12,
        message: 'Integrated user-facing synergy',
        created_at: 12,
        sender_id: 1,
    },
    {
        id: 13,
        message: 'Implemented upward-trending internet solution',
        created_at: 13,
        sender_id: 1,
    },
    {
        id: 14,
        message: 'Multi-lateral disintermediate time-frame',
        created_at: 14,
        sender_id: 2,
    },
    {
        id: 15,
        message: 'Pre-emptive real-time project',
        created_at: 15,
        sender_id: 1,
    },
    {
        id: 16,
        message: 'Compatible interactive hierarchy',
        created_at: 16,
        sender_id: 1,
    },
    {
        id: 17,
        message: 'Ergonomic composite local area network',
        created_at: 17,
        sender_id: 1,
    },
    {
        id: 18,
        message: 'User-centric full-range moratorium',
        created_at: 18,
        sender_id: 1,
    },
    {
        id: 19,
        message: 'Secured 24/7 knowledge user',
        created_at: 19,
        sender_id: 1,
    },
    {
        id: 20,
        message: 'Ergonomic multi-state ability',
        created_at: 20,
        sender_id: 1,
    },
    {
        id: 21,
        message: 'Visionary didactic product',
        created_at: 21,
        sender_id: 1,
    },
    {
        id: 22,
        message: 'Distributed motivating superstructure',
        created_at: 22,
        sender_id: 2,
    },
    {
        id: 23,
        message: 'User-friendly foreground policy',
        created_at: 23,
        sender_id: 1,
    },
    {
        id: 24,
        message: 'Programmable user-facing moderator',
        created_at: 24,
        sender_id: 1,
    },
    {
        id: 25,
        message: 'Reactive object-oriented parallelism',
        created_at: 25,
        sender_id: 2,
    },
];
